<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ShivaleelaHMBP" ignored="0" name="retry" tests="8" failures="2" timestamp="15 Mar 2018 07:45:30 GMT" time="0.217" errors="0">
  <testcase name="test" time="0.02" classname="com.samp.farrier.tests.Test">
    <skipped/>
  </testcase> <!-- test -->
  <testcase name="test" time="0.006" classname="com.samp.farrier.tests.Test">
    <skipped/>
  </testcase> <!-- test -->
  <testcase name="test" time="0.012" classname="com.samp.farrier.tests.Test">
    <skipped/>
  </testcase> <!-- test -->
  <testcase name="test" time="0.004" classname="com.samp.farrier.tests.Test">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.samp.farrier.tests.Test.test(Test.java:16)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test1" time="0.001" classname="com.samp.farrier.tests.Test">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="com.samp.farrier.tests.Test">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="com.samp.farrier.tests.Test">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.004" classname="com.samp.farrier.tests.Test">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.samp.farrier.tests.Test.test1(Test.java:31)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- retry -->
